# Build and Push Hugo site to gh-pages
name: build-push

# trigger events
on:
  workflow_dispatch:

  push:
    branches:
      - "main"

    paths:
      - "archtypes/**/*"
      - "assets/**/*"
      - "exampleSite/**/*"
      - "i18n/**/*"
      - "layouts/**/*"
      - "static/**/*"

    # paths-ignore:
    #   - ".docker/**"
    #   - ".example/**"
    #   - ".github/**"
    #   - "README.md"
    #   - "*.txt"
    #   - "*.sh"
    #   - ".env.example"
    #   - ".editorconfig"
    #   - "images/**"
    #   - "docker-compose.yml"

jobs:
  # Build & Push hugo site
  hugo:
    name: build-push
    if: ${{ github.repository == 'sujaykumarh/hugo-notebook' }}

    runs-on: ubuntu-latest
    steps:
      # Pull Source Code
      - name: ✅ Checkout Source
        uses: actions/checkout@v2

      - name: 🔨 Build Hugo Site
        run: |
          sh build.sh --baseUrl https://notebook-demo.sujaykumarh.com

      - name: ℹ️ Setup files in dist
        run: |
          cp README.md dist/dist-readme.md
          touch dist/.nojekyll
          if [ -f "CNAME" ]; then cp CNAME dist/CNAME; fi

      - name: 🚀 Push to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          MESSAGE: "🔨 Build gh-pages from {target-branch} {sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
